server:
  port: 9030
spring:
  mail:
    host: smtp.163.com
    username: lwd_kop@163.com
    password: GNPEKSKNWNFBGIZF
  rabbitmq:
    host: 192.168.64.152
    username: admin
    password: admin
    port: 5672
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lwd
    url: jdbc:mysql://localhost:3306/demo3
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijk
      expire: 7
